name: Update Gradle Wrapper
on: [push, pull_request]

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  build:
    runs-on: ubuntu-latest
    name: gradle-up
    steps:
    - uses: actions/checkout@v2
    - uses: rahulsom/gradle-up@v0.2.0
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
